# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-24 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='default_image.jpeg', upload_to=''),
        ),
    ]
